export const colors  = [
    { label: 'Rouge', value: '#ff0000' },
    { label: 'Vert', value: '#00ff00' },
    { label: 'Bleu', value: '#0000ff' },
    { label: 'Jaune', value: '#ffff00' },
    { label: 'Cyan', value: '#00ffff' },
    { label: 'Magenta', value: '#ff00ff' },
    { label: 'Noir', value: '#000000' },
    { label: 'Gris foncé', value: '#808080' },
    { label: 'Gris clair', value: '#c0c0c0' },
    { label: 'Blanc', value: '#ffffff' },
    { label: 'Marron', value: '#800000' },
    { label: 'Olive foncé', value: '#556b2f' },
    { label: 'Vert foncé', value: '#006400' },
    { label: 'Violet foncé', value: '#9400d3' },
    { label: 'Turquoise foncé', value: '#00ced1' },
    { label: 'Bleu marine', value: '#000080' },
    { label: 'Gris', value: '#808080' },
    { label: 'Citron vert', value: '#00ff00' },
    { label: 'Turquoise', value: '#40e0d0' },
    { label: 'Fuchsia', value: '#ff00ff' },
    { label: 'Orange', value: '#ffa500' },
    { label: 'Marron clair', value: '#cd853f' },
    { label: 'Beige', value: '#f5f5dc' },
    { label: 'Rose', value: '#ffc0cb' },
    { label: 'Rouge foncé', value: '#8b0000' },
    { label: 'Vert olive', value: '#808000' },
    { label: 'Vert clair', value: '#00ff00' },
    { label: 'Violet', value: '#800080' },
    { label: 'Turquoise clair', value: '#00ffff' },
    { label: 'Bleu clair', value: '#add8e6' },
    { label: 'Argent', value: '#c0c0c0' },
    { label: 'Vert citron', value: '#32cd32' },
    { label: 'Aqua', value: '#00ffff' },
    { label: 'Fuchsia clair', value: '#ff77ff' },
    { label: 'Orange foncé', value: '#ff8c00' },
    { label: 'Brun', value: '#a52a2a' },
    { label: 'Or', value: '#ffd700' },
    { label: 'Vert pâle', value: '#98fb98' },
    { label: 'Violet clair', value: '#e6e6fa' },
    { label: 'Turquoise pâle', value: '#afeeee' },
    { label: 'Bleu pâle', value: '#b0e0e6' },
    { label: 'Or pâle', value: '#eee8aa' },
    { label: 'Rose pâle', value: '#ffb6c1' },
    { label: 'Brun clair', value: '#d2b48c' },
    { label: 'Or rose', value: '#ffc0cb' },
    { label: 'Beige clair', value: '#f5f5dc' },
    { label: 'Bleu acier', value: '#4682b4' },
    { label: 'Gris ardoise', value: '#708090' },
    { label: 'Vert olive pâle', value: '#bdb76b' },
    { label: 'Vert mer', value: '#2e8b57' },
];
